apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-app
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chatroom-cont
        image: abdullah77044/chatroom:2
        ports:
        - containerPort: 8080